Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:custom.settings.DB_USERNAME}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "${self:custom.settings.DB_USERNAME}"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  ERPDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBName: "ERPDatabase"
      MasterUsername: ${self:custom.settings.DB_USERNAME}
      MasterUserPassword: ${self:custom.settings.DB_PASSWORD}
      Engine: mysql
      EngineVersion: "8.0"
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "RDS subnet group"
      SubnetIds:
        - !Ref SubnetOne
        - !Ref SubnetTwo
      Tags:
        - Key: "Name"
          Value: "RDSSubnetGroup"

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref Secret
      TargetId: !Ref ERPDatabase
      TargetType: AWS::RDS::DBInstance
